version: "2"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=currency
      - POSTGRES_PASSWORD=currency
    ports:
      - 5432:5432
    restart: always

  db-test:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5433:5432
    restart: always
